import {injectable} from 'inversify';
import {smartBloomConfig} from '#root/config/smartBloom.js';
import {ITranscriptChunk, json3ToChunks} from '../utils/Transcript.js';

export type CaptionOutcome =
  | {
      kind: 'FOUND';
      chunks: ITranscriptChunk[];
      language: string;
      autoGenerated: boolean;
      durationSeconds?: number;
    }
  | {
      kind: 'MISSING';
      reason: 'NO_CAPTIONS' | 'UNAVAILABLE' | 'FETCH_FAILED';
      detail: string;
    };

/**
 * Reads a public YouTube video's captions so Smart Bloom can build a transcript
 * without downloading or transcribing any audio.
 *
 * YouTube offers no public API for reading captions on videos you do not own, so
 * this uses the player endpoint its own mobile apps call. The watch-page caption
 * links now require a proof-of-origin token and come back empty; the mobile-app
 * clients' links do not. This is an unofficial interface and can change without
 * notice, so every failure is reported as a reason the page can act on (ask the
 * instructor to upload the transcript) rather than thrown.
 */
@injectable()
export class YouTubeCaptionService {
  private static readonly PLAYER_URL =
    'https://www.youtube.com/youtubei/v1/player?prettyPrint=false';

  private static readonly CLIENTS = [
    {
      client: {
        clientName: 'ANDROID',
        clientVersion: '20.10.38',
        androidSdkVersion: 30,
        hl: 'en',
      },
      userAgent:
        'com.google.android.youtube/20.10.38 (Linux; U; Android 11) gzip',
    },
    {
      client: {
        clientName: 'IOS',
        clientVersion: '20.10.4',
        deviceModel: 'iPhone16,2',
        hl: 'en',
      },
      userAgent:
        'com.google.ios.youtube/20.10.4 (iPhone16,2; U; CPU iOS 18_3 like Mac OS X)',
    },
  ];

  async fetchCaptions(videoId: string): Promise<CaptionOutcome> {
    let lastDetail = 'no response from YouTube';
    let sawPlayableVideo = false;

    for (const {client, userAgent} of YouTubeCaptionService.CLIENTS) {
      let player: any;
      try {
        player = await this.postJson(
          YouTubeCaptionService.PLAYER_URL,
          {context: {client}, videoId},
          userAgent,
        );
      } catch (error) {
        lastDetail = `player request failed (${client.clientName}): ${(error as Error).message}`;
        continue;
      }

      const status = player?.playabilityStatus?.status;
      if (status && status !== 'OK') {
        lastDetail = `YouTube reports the video as ${status}: ${player?.playabilityStatus?.reason ?? 'no reason given'}`;
        continue;
      }
      sawPlayableVideo = true;

      const tracks: any[] =
        player?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
      const durationSeconds =
        Number(player?.videoDetails?.lengthSeconds) || undefined;
      if (!tracks.length) {
        return {
          kind: 'MISSING',
          reason: 'NO_CAPTIONS',
          detail: 'This video has no captions on YouTube.',
        };
      }

      const track = this.pickTrack(tracks);
      try {
        const url = `${String(track.baseUrl).replace(/&fmt=[^&]*/g, '')}&fmt=json3`;
        const json3 = await this.getJson(url, userAgent);
        const chunks = json3ToChunks(json3);
        if (chunks.length) {
          return {
            kind: 'FOUND',
            chunks,
            language: String(track.languageCode ?? ''),
            autoGenerated: track.kind === 'asr',
            durationSeconds,
          };
        }
        lastDetail = `caption track (${client.clientName}) came back empty`;
      } catch (error) {
        lastDetail = `caption download failed (${client.clientName}): ${(error as Error).message}`;
      }
    }

    return {
      kind: 'MISSING',
      reason: sawPlayableVideo ? 'FETCH_FAILED' : 'UNAVAILABLE',
      detail: lastDetail,
    };
  }

  /** Prefer a human-made track in a preferred language, then auto-generated, then anything. */
  private pickTrack(tracks: any[]): any {
    const languages = smartBloomConfig.captionLanguages;
    const lang = (track: any) =>
      String(track.languageCode ?? '')
        .toLowerCase()
        .split('-')[0];
    for (const code of languages) {
      const manual = tracks.find(
        track => lang(track) === code && track.kind !== 'asr',
      );
      if (manual) return manual;
      const auto = tracks.find(track => lang(track) === code);
      if (auto) return auto;
    }
    return tracks.find(track => track.kind !== 'asr') ?? tracks[0];
  }

  private async postJson(
    url: string,
    body: unknown,
    userAgent: string,
  ): Promise<any> {
    return this.request(url, {
      method: 'POST',
      headers: {'Content-Type': 'application/json', 'User-Agent': userAgent},
      body: JSON.stringify(body),
    });
  }

  private async getJson(url: string, userAgent: string): Promise<any> {
    return this.request(url, {
      method: 'GET',
      headers: {'User-Agent': userAgent},
    });
  }

  private async request(url: string, init: RequestInit): Promise<any> {
    const controller = new AbortController();
    const timer = setTimeout(
      () => controller.abort(),
      smartBloomConfig.captionTimeoutMs,
    );
    try {
      const res = await fetch(url, {...init, signal: controller.signal});
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const text = await res.text();
      if (!text.trim()) throw new Error('empty body');
      return JSON.parse(text);
    } finally {
      clearTimeout(timer);
    }
  }
}
