// Smart Bloom direct path: runs Smart Bloom without the AI server.
// Transcript from YouTube captions or an uploaded .srt/.vtt file; segmentation
// and questions from MiniMax on the ViBe backend. Stateless: the page keeps the
// transcript, segment map and questions between calls.

export type TranscriptChunk = { timestamp: [number, number]; text: string };

export interface IDirectTranscriptResult {
  available: boolean;
  source?: "YOUTUBE_CAPTIONS" | "UPLOADED_FILE";
  language?: string;
  autoGenerated?: boolean;
  durationSeconds?: number;
  transcript?: { chunks: TranscriptChunk[] };
  reason?: string;
  message?: string;
}

export interface IDirectSegmentResult {
  segmentMap: number[];
  method: "MODEL" | "EVEN_SPLIT";
  warning?: string;
}

export interface IDirectQuestionsResult {
  questions: Record<string, unknown>[];
  failedLevels: string[];
  dropped: number;
}

export interface IDirectUploadSummary {
  videoItems: number;
  quizItems: number;
  questionBanks: number;
  questionsCreated: number;
  questionsSkipped: number;
}

const BASE_URL = import.meta.env.VITE_BASE_URL;

async function post<T>(path: string, body: unknown): Promise<T> {
  const token = localStorage.getItem("firebase-auth-token");
  if (!token) throw new Error("You are signed out. Please sign in again.");

  let response: Response;
  try {
    response = await fetch(`${BASE_URL}/smart-bloom/direct${path}`, {
      method: "POST",
      mode: "cors",
      credentials: "include",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
      body: JSON.stringify(body),
    });
  } catch {
    throw new Error("Could not reach the ViBe server. Check your connection and try again.");
  }

  const text = await response.text();
  let data: unknown = null;
  try {
    data = text ? JSON.parse(text) : null;
  } catch {
    data = null;
  }
  if (!response.ok) {
    const body = (data ?? {}) as { message?: unknown; error?: unknown };
    const message = body.message || body.error || text || response.statusText;
    throw new Error(String(message));
  }
  return data as T;
}

export const smartBloomDirectAPI = {
  transcriptFromYouTube: (versionId: string, videoUrl: string) =>
    post<IDirectTranscriptResult>("/transcript/youtube", { versionId, videoUrl }),

  transcriptFromFile: (versionId: string, fileName: string, content: string) =>
    post<IDirectTranscriptResult>("/transcript/file", { versionId, fileName, content }),

  segment: (params: {
    versionId: string;
    chunks: TranscriptChunk[];
    strategy: "DEFAULT" | "CONCEPT_END";
    minSegmentSeconds: number;
    videoEndSeconds?: number;
  }) => post<IDirectSegmentResult>("/segments", params),

  generateQuestions: (params: {
    versionId: string;
    segmentNumber: number;
    startSeconds: number;
    endSeconds: number;
    segmentText: string;
    bloomTargets: Record<string, number>;
    questionTypes: string[];
    instructions?: string;
  }) => post<IDirectQuestionsResult>("/questions", params),

  upload: (params: {
    versionId: string;
    moduleId: string;
    sectionId: string;
    videoUrl: string;
    segmentMap: number[];
    questions: unknown[];
    distribution?: Record<string, number>;
    videoItemBaseName?: string;
    quizItemBaseName?: string;
  }) => post<IDirectUploadSummary>("/upload", params),
};

/** Transcript text spoken inside [start, end), by chunk start time. */
export const textInWindow = (chunks: TranscriptChunk[], start: number, end: number): string =>
  chunks
    .filter((chunk) => chunk.timestamp[0] >= start && chunk.timestamp[0] < end)
    .map((chunk) => chunk.text)
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();
